[[intro]]
== You Know, for Search...

Elasticsearch is an open-source search engine built on top of
https://lucene.apache.org/core/[Apache Lucene(TM)], a full-text search-engine
library.((("Apache Lucene")))((("Lucene")))  Lucene is arguably the most advanced, high-performance, and fully featured
search engine library in existence today--both open source and proprietary.

Elasticsearch 是基于 https://lucene.apache.org/core/[Apache Lucene(TM)] ，一个全文检索引擎库之上构建的开源搜索引擎。
((("Apache Lucene")))((("Lucene")))  Lucene 无论在当前的开源或收费领域，都毋庸置疑是最先进、高性能且全功能的搜索引擎库。


But Lucene is just a library. To leverage its power, you need to work in Java
and to integrate Lucene directly with your application. Worse, you will likely
require a degree in information retrieval to understand how it works.  Lucene
is _very_ complex.

但是 Lucene 只是一个库。为了撬动它的能力，你需要使用 Java 进行开发，并将 Lucene 与你的应用进行集成。更糟的是，
为了搞清楚它的工作原理，你可能会需要一个信息检索学位。Lucene _非常_复杂。

Elasticsearch is also written in Java((("Java"))) and uses Lucene internally for all of
its indexing and searching, but it aims to make full-text search easy by hiding
the complexities of Lucene behind a simple, coherent, RESTful API.

Elasticsearch 同样由 Java((("Java"))) 编写，并在内部使用 Lucene 来完成它的所有索引和搜索功能，
但它的目标是将 Lucene 的复杂操作通过通过简单、容易理解、 RESTful API方式更为简洁的实现全文检索。

However, Elasticsearch is much more than just Lucene and much more than
``just'' full-text search.((("Elasticsearch", "capabilities"))) It can also be described as follows:

然而， Elasticsearch 不仅仅是 Lunece，也并不止是一个全文检索工具。((("Elasticsearch", "capabilities")))它也可以像以下这样描述：

* A distributed real-time document store where _every field_ is indexed and
  searchable
* A distributed search engine with real-time analytics
* Capable of scaling to hundreds of servers and petabytes of structured
  and unstructured data

And it packages up all this functionality into a standalone server that
your application can talk to via a simple RESTful API, using a web client from
your favorite programming language, or even from the command line.

It is easy to get started with Elasticsearch. It ships with sensible defaults
and hides complicated search theory away from beginners. It _just works_,
right out of the box. With minimal understanding, you can soon become
productive.((("Elasticsearch", "installing")))

As your knowledge grows, you can leverage more of Elasticsearch's advanced
features. The entire engine is configurable and flexible. Pick and choose
from the advanced features to tailor Elasticsearch to your problem domain.

You can ((("Apache 2 license"))) download, use, and modify Elasticsearch free of charge. 
It is available under the http://www.apache.org/licenses/LICENSE-2.0.html[Apache 2 license],
one of the most flexible open source licenses available. The source is hosted on GitHub
at https://github.com/elastic/elasticsearch[github.com/elastic/elasticsearch]. See
https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md[Contributing to 
Elasticsearch] if you would like to join our amazing community of contributors!

If you have any questions related to Elasticsearch, including specific features, 
language clients and plugins, join the conversation at 
https://discuss.elastic.co[discuss.elastic.co]. 

.The Mists of Time
***************************************

Many years ago, a newly married unemployed developer called Shay Banon
followed his wife to London, where she was studying to be a chef. While looking
for gainful employment, he started playing with an early version of Lucene,
with the intent of building his wife a recipe search engine.

Working directly with Lucene can be tricky, so Shay started work on an
abstraction layer to make it easier for Java programmers to add search to
their applications.  He released this as his first open source project, called
Compass.

Later Shay took a job working in a high-performance, distributed environment
with in-memory data grids.  The need for a high-performance, real-time,
distributed search engine was obvious, and he decided to rewrite the Compass
libraries as a standalone server called Elasticsearch.

The first public release came out in February 2010.  Since then, Elasticsearch
has become one of the most popular projects on GitHub with commits from over
300 contributors.  A company has formed around Elasticsearch to provide
commercial support and to develop new features, but Elasticsearch is, and
forever will be, open source and available to all.

Shay's wife is still waiting for the recipe search...

***************************************
